name: "classifier_postprocessor"
backend: "python"

max_batch_size: 8
instance_group [
  {
    kind: KIND_CPU
  }
]
dynamic_batching {
  preferred_batch_size: [ 4, 8 ]
  max_queue_delay_microseconds: 100
}

input [
  {
    name: "model_output"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]
output [
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]